version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/blot-parser"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "amitpadole"
    assignees:
      - "amitpadole"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "amitpadole"
    assignees:
      - "amitpadole"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker (if used in future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "amitpadole"
    assignees:
      - "amitpadole"
    commit-message:
      prefix: "chore"
      include: "scope"
