AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified Parent CloudFormation Stack for Blot Parser - Only S3 and VPC'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: blot-parser
    Description: Project name for resource naming
  
  AWSAccountId:
    Type: String
    Description: AWS Account ID
    MinLength: 12
    MaxLength: 12
    AllowedPattern: '^[0-9]{12}$'

Resources:
  # S3 Resources Stack (must be first to create deployment bucket)
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${ProjectName}-deployments-${Environment}-${AWSAccountId}.s3.${AWS::Region}.amazonaws.com/cloudformation/s3.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        AWSAccountId: !Ref AWSAccountId
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # VPC Resources Stack (depends on S3Stack for deployment bucket)
  VPCStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub 'https://${ProjectName}-deployments-${Environment}-${AWSAccountId}.s3.${AWS::Region}.amazonaws.com/cloudformation/vpc.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # VPC Outputs
  VpcId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name: !Sub '${ProjectName}-VpcId-${Environment}'
  
  VpcCidrBlock:
    Description: VPC CIDR Block
    Value: !GetAtt VPCStack.Outputs.VpcCidrBlock
    Export:
      Name: !Sub '${ProjectName}-VpcCidrBlock-${Environment}'
  
  PublicSubnetId:
    Description: Public Subnet ID (Single AZ for cost optimization)
    Value: !GetAtt VPCStack.Outputs.PublicSubnetId
    Export:
      Name: !Sub '${ProjectName}-PublicSubnetId-${Environment}'
  
  PrivateSubnetId:
    Description: Private Subnet ID (Single AZ for cost optimization)
    Value: !GetAtt VPCStack.Outputs.PrivateSubnetId
    Export:
      Name: !Sub '${ProjectName}-PrivateSubnetId-${Environment}'
  
  DefaultSecurityGroupId:
    Description: Default Security Group ID
    Value: !GetAtt VPCStack.Outputs.DefaultSecurityGroupId
    Export:
      Name: !Sub '${ProjectName}-DefaultSecurityGroupId-${Environment}'

  # S3 Outputs
  InputBucketName:
    Description: S3 bucket for input files
    Value: !GetAtt S3Stack.Outputs.InputBucketName
    Export:
      Name: !Sub '${ProjectName}-InputBucket-${Environment}'
  
  DeploymentBucketName:
    Description: S3 bucket for Lambda deployments
    Value: !GetAtt S3Stack.Outputs.DeploymentBucketName
    Export:
      Name: !Sub '${ProjectName}-DeploymentBucket-${Environment}'
