AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Deployment Bucket for Astra - Must be created first'

Parameters:
  Environment:
    Type: String
    Description: Environment name
  
  ProjectName:
    Type: String
    Description: Project name for resource naming
  
  AWSAccountId:
    Type: String
    Description: AWS Account ID

Resources:
  # S3 Bucket for Lambda deployments (must be created first)
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-deployments-${Environment}-${AWSAccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: LambdaDeployments

Outputs:
  DeploymentBucketName:
    Description: S3 bucket for Lambda deployments
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub '${ProjectName}-DeploymentBucket-${Environment}'
  
  DeploymentBucketArn:
    Description: S3 bucket ARN for deployments
    Value: !GetAtt DeploymentBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-DeploymentBucketArn-${Environment}'
